- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: reboot_required_file == false
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when: reboot_required_file == false
