- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: not reboot is defined
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when: not reboot is defined
