do_token                  = ""
project_name              = ""
volume_name               = ""
region                    = "fra1"
size                      = "s-1vcpu-2gb"
terraform_public_ssh_key  = "../ssh/ssh.pub"
terraform_private_ssh_key = "../ssh/ssh"
my_ip_address             = ""
